### PR TITLE
README: Update instructions

### PR DESCRIPTION
**Pull request by networkException**
Attempting to build with 3.10 results in the following error:

`ImportError: cannot import name 'Mapping' from 'collections'`

image

### CODE REVIEW

**Comment by networkException** [comment]
I haven't included Windows SDK version information in the patch since its already well documented in the chromium guide:
image

**Comment by mmvanheusden** [comment]
Merge please

**Comment by networkException** [comment]
Well I can only second that statement

**Comment by mmvanheusden** [comment]
#106 is merged so now this one fan be merged too right?

**Comment by networkException** [comment]
Is this still up to date for current versions (@teeminus @Nifury)?

**Comment by teeminus** [comment]
I am using python 3.10.4 without any problems.

The notes about the windows python wrapper however would be a great addition to the readme. I just setup a dedicated compile machine for this project and ran into the exact same problem.

If I remember correctly my problem was that the python executable installed by the python installer is called python.exe but there is a windows wrapper for both py.exe and python3.exe. I manually created a copy of python.exe and renamed the copies accordingly and now everything works fine even without removing the windows python wrappers. But that does not have to be true for other systems...
